### ISSUE TITLE
Add bcftools to docker image

### ISSUE THREAD

**Issue by mbhall88** [TimD1/vcfdist#21]
Again, thank you for the awesome work on this method - I love it.

It would be quite handy to have bcftools available in the docker image. Would this be something you'd be open to adding? (Totally fine if not as it is a convenience not a necessity)

**Comment by TimD1** [comment]
I can easily add it to the Dockerfile if that makes things easier. I'm busy this week, but should get around to these suggestions after that. In the meantime, feel free to keep opening issues.

**Comment by mbhall88** [comment]
No rush at all. Thanks again. And sorry for all the issues 😬 none of them are crucial though - I have workarounds for them all.

**Comment by TimD1** [comment]
bcftools is now included in the vcfdist v2.3.4 Docker image
