### ISSUE TITLE
time issue

### ISSUE THREAD

**Issue by aaaniich** [TimD1/vcfdist#32]
Hi. Thank you so much for your hard work and creating a powerful tool! 

Could you please advise. As I understand phasing is a mandatory part before analyzing, I did it with whatshap. then I run the tool, but my calculations last for more than 2 days. I am worried that i am doing something wrong and i need to abort the process. But i don't understand where i might have gone mistaken.
 Should I go back to preprocessing my data? Or does the calculation still have a chance to end successfully?

Also I have this warnings when started:
[WARN  vcfdist 18:15:08] 171157 variants missing PS tags in QUERY VCF, kept
[WARN  vcfdist 18:15:08] 171157 variants with unphased genotypes in QUERY VCF, skipped
[WARN  vcfdist 18:15:08] 1003 large (size > 5000) variants in QUERY VCF, skipped
[WARN  vcfdist 18:15:08] 19076 overlapping variants in QUERY VCF, skipped
[WARN  vcfdist 18:15:08] 163462 complex (CPX) variants in QUERY VCF, split into INS + DEL
[WARN  vcfdist 18:15:08] 'PS' tag not defined in TRUTH VCF header, assuming one phase set per contig
[WARN  vcfdist 18:15:13] 1120711 variants with unknown (./.) alleles in TRUTH VCF, skipped
[WARN  vcfdist 18:15:13] 73320 variants spanned by deletion in TRUTH VCF, skipped
[WARN  vcfdist 18:15:13] 901 large (size > 5000) variants in TRUTH VCF, skipped
[WARN  vcfdist 18:15:13] 22 overlapping variants in TRUTH VCF, skipped
[WARN  vcfdist 18:15:13] 37 complex (CPX) variants in TRUTH VCF, split into INS + DEL

**Comment by TimD1** [comment]
If your analysis has been running for more than a day, something is likely wrong, though it is possible your system is short on RAM. Could you please provide the inputs you used here, as well as a full log of the run (including INFO messages)?

**Comment by aaaniich** [comment]
> If your analysis has been running for more than a day, something is likely wrong, though it is possible your system is short on RAM. Could you please provide the inputs you used here, as well as a full log of the run (including INFO messages)?

I checked, my RAM should have been enough, but maybe I miscalculated. I ended up dividing the files by chromosome and the analysis went. One chromosome takes 17-18 hours to process, so I just ran it in a loop. The results look correct, but if such time looks inadequate I can throw infomation on my data. 

Anyway, thanks for your reply and your work!
